version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Testcontainers_Template/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User Id=sa;Password=P@ssw0rd123!;Encrypt=true;TrustServerCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver2025
    environment:
      SA_PASSWORD: "P@ssw0rd123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd123! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
